"""Keyword packs: the searchable vocabulary the generator draws from.

Every pack referenced anywhere in ``profiles.py`` or the CLI screens exists
here. The original codebase referenced ``ai_services``, ``react``, and
``angular`` packs that were never defined (see AUDIT.md) — those are filled
in below, along with new packs for WordPress, CI/CD, Bitbucket, monitoring,
email, and sector-specific document exposure (medical/finance/government/
education).
"""
from __future__ import annotations

from .models import Keyword

KeywordPack = dict[str, object]  # {"name": str, "keywords": list[Keyword]}

KEYWORD_PACKS: dict[str, KeywordPack] = {
    "aws": {"name": "Amazon Web Services", "keywords": [
        Keyword("AWS_ACCESS_KEY_ID", "cloud", 9, ("aws", "credentials"), technology="aws"),
        Keyword("AWS_SECRET_ACCESS_KEY", "cloud", 9, ("aws", "credentials"), technology="aws"),
        Keyword("aws_access_key_id", "cloud", 9, ("aws", "credentials"), technology="aws"),
        Keyword("aws_secret_access_key", "cloud", 9, ("aws", "credentials"), technology="aws"),
        Keyword("s3.amazonaws.com", "cloud", 7, ("aws", "s3"), technology="aws"),
        Keyword("AWS_S3_BUCKET", "cloud", 7, ("aws", "s3"), technology="aws"),
        Keyword("IAM Role", "cloud", 7, ("aws", "iam"), technology="aws"),
        Keyword("lambda_function", "cloud", 5, ("aws", "lambda"), technology="aws"),
        Keyword("Bucket:", "cloud", 6, ("aws", "s3"), technology="aws"),
        Keyword("elasticbeanstalk", "cloud", 5, ("aws", "eb"), technology="aws"),
        Keyword("AWS_SESSION_TOKEN", "cloud", 9, ("aws", "credentials"), technology="aws"),
        Keyword("cloudfront.net", "cloud", 4, ("aws", "cdn"), technology="aws"),
    ]},
    "azure": {"name": "Microsoft Azure", "keywords": [
        Keyword("AZURE_CLIENT_ID", "cloud", 9, ("azure", "credentials"), technology="azure"),
        Keyword("AZURE_CLIENT_SECRET", "cloud", 9, ("azure", "credentials"), technology="azure"),
        Keyword("AZURE_TENANT_ID", "cloud", 8, ("azure", "credentials"), technology="azure"),
        Keyword("azure_storage", "cloud", 7, ("azure", "storage"), technology="azure"),
        Keyword(".azurewebsites.net", "cloud", 5, ("azure", "appservice"), technology="azure"),
        Keyword("azure_keyvault", "cloud", 8, ("azure", "security"), technology="azure"),
        Keyword("blob.core.windows.net", "cloud", 6, ("azure", "storage"), technology="azure"),
    ]},
    "gcp": {"name": "Google Cloud Platform", "keywords": [
        Keyword("GOOGLE_APPLICATION_CREDENTIALS", "cloud", 9, ("gcp", "credentials"), technology="gcp"),
        Keyword("GOOGLE_API_KEY", "cloud", 8, ("gcp", "api"), technology="gcp"),
        Keyword("google_cloud_storage", "cloud", 7, ("gcp", "storage"), technology="gcp"),
        Keyword(".appspot.com", "cloud", 5, ("gcp", "appengine"), technology="gcp"),
        Keyword("storage.googleapis.com", "cloud", 7, ("gcp", "storage"), technology="gcp"),
        Keyword("service_account.json", "cloud", 9, ("gcp", "credentials"), technology="gcp"),
    ]},
    "firebase": {"name": "Firebase", "keywords": [
        Keyword("firebaseio.com", "cloud", 7, ("firebase", "database"), technology="firebase"),
        Keyword("firebaseapp.com", "cloud", 5, ("firebase", "hosting"), technology="firebase"),
        Keyword("firebase", "cloud", 6, ("firebase",), technology="firebase"),
        Keyword("FIREBASE_CONFIG", "cloud", 8, ("firebase", "config"), technology="firebase"),
        Keyword("apiKey", "cloud", 6, ("firebase", "config"), technology="firebase"),
    ]},
    "cloudflare": {"name": "Cloudflare", "keywords": [
        Keyword("CLOUDFLARE_API_KEY", "cloud", 9, ("cloudflare", "credentials"), technology="cloudflare"),
        Keyword("cloudflare_email", "cloud", 7, ("cloudflare",), technology="cloudflare"),
        Keyword("CF_API_KEY", "cloud", 9, ("cloudflare", "api"), technology="cloudflare"),
        Keyword("CF_API_TOKEN", "cloud", 9, ("cloudflare", "api"), technology="cloudflare"),
    ]},
    "secrets": {"name": "Secrets & Credentials", "keywords": [
        Keyword("password", "secrets", 8, ("credentials",)),
        Keyword("passwd", "secrets", 8, ("credentials",)),
        Keyword("secret_key", "secrets", 9, ("credentials",)),
        Keyword("SECRET_KEY", "secrets", 9, ("credentials",)),
        Keyword("api_key", "secrets", 9, ("api", "credentials")),
        Keyword("API_KEY", "secrets", 9, ("api", "credentials")),
        Keyword("api_secret", "secrets", 9, ("api", "credentials")),
        Keyword("access_token", "secrets", 9, ("auth", "token")),
        Keyword("bearer_token", "secrets", 9, ("auth", "token")),
        Keyword("client_secret", "secrets", 9, ("oauth", "credentials")),
        Keyword("private_key", "secrets", 9, ("crypto", "key")),
        Keyword("jwt_secret", "secrets", 9, ("jwt", "auth")),
        Keyword("credentials", "secrets", 7, ("credentials",)),
        Keyword("slack_token", "secrets", 8, ("slack",)),
        Keyword("discord_token", "secrets", 8, ("discord",)),
        Keyword("stripe_secret_key", "secrets", 9, ("payments", "stripe")),
        Keyword("twilio_auth_token", "secrets", 8, ("twilio",)),
    ]},
    "passwords": {"name": "Passwords", "keywords": [
        Keyword("password=", "secrets", 9, ("password",)),
        Keyword("passwd=", "secrets", 9, ("password",)),
        Keyword("pwd=", "secrets", 8, ("password",)),
        Keyword("db_password", "secrets", 9, ("database", "password")),
        Keyword("DB_PASSWORD", "secrets", 9, ("database", "password")),
        Keyword("mysql_password", "secrets", 9, ("mysql",)),
        Keyword("root_password", "secrets", 9, ("root",)),
        Keyword("admin_password", "secrets", 9, ("admin",)),
    ]},
    "database": {"name": "Databases", "keywords": [
        Keyword("mysql_connection", "database", 7, ("mysql",)),
        Keyword("postgresql", "database", 7, ("postgres",)),
        Keyword("mongodb", "database", 7, ("mongo",)),
        Keyword("redis", "database", 6, ("redis",)),
        Keyword("DATABASE_URL", "database", 8, ("connection",)),
        Keyword("phpmyadmin", "database", 6, ("mysql", "admin")),
        Keyword("elasticsearch", "database", 6, ("elastic",)),
        Keyword("mongodb://", "database", 8, ("mongo", "connection")),
        Keyword("postgres://", "database", 8, ("postgres", "connection")),
    ]},
    "docker": {"name": "Docker", "keywords": [
        Keyword("DOCKER_HOST", "devops", 7, ("docker",), technology="docker"),
        Keyword("DOCKER_PASSWORD", "devops", 9, ("docker", "credentials"), technology="docker"),
        Keyword("docker-compose.yml", "devops", 6, ("docker", "compose"), technology="docker"),
        Keyword("Dockerfile", "devops", 4, ("docker",), technology="docker"),
        Keyword("docker_registry", "devops", 7, ("docker", "registry"), technology="docker"),
    ]},
    "kubernetes": {"name": "Kubernetes", "keywords": [
        Keyword("kubeconfig", "devops", 9, ("kubernetes",), technology="kubernetes"),
        Keyword("kubernetes_secret", "devops", 8, ("kubernetes", "secrets"), technology="kubernetes"),
        Keyword("kubectl", "devops", 5, ("kubernetes",), technology="kubernetes"),
        Keyword("helm_chart", "devops", 5, ("kubernetes", "helm"), technology="kubernetes"),
        Keyword(".kube/config", "devops", 9, ("kubernetes", "config"), technology="kubernetes"),
    ]},
    "git": {"name": "Git & Repositories", "keywords": [
        Keyword(".git/config", "devops", 9, ("git", "config"), technology="git"),
        Keyword(".gitignore", "devops", 5, ("git",), technology="git"),
        Keyword("github_token", "devops", 9, ("github", "token"), technology="git"),
        Keyword("github_actions", "devops", 5, ("github", "ci"), technology="git"),
        Keyword("gitlab_ci", "devops", 6, ("gitlab", "ci"), technology="git"),
        Keyword("id_rsa", "devops", 9, ("ssh", "key"), technology="git"),
    ]},
    "bitbucket": {"name": "Bitbucket", "keywords": [
        Keyword("bitbucket-pipelines.yml", "devops", 6, ("bitbucket", "ci"), technology="bitbucket"),
        Keyword("BITBUCKET_APP_PASSWORD", "devops", 9, ("bitbucket", "credentials"), technology="bitbucket"),
        Keyword("bitbucket.org", "devops", 4, ("bitbucket",), technology="bitbucket"),
    ]},
    "terraform": {"name": "Terraform", "keywords": [
        Keyword("terraform.tfstate", "devops", 8, ("terraform", "state"), technology="terraform"),
        Keyword("main.tf", "devops", 5, ("terraform",), technology="terraform"),
        Keyword("variables.tf", "devops", 5, ("terraform",), technology="terraform"),
        Keyword(".terraform", "devops", 6, ("terraform",), technology="terraform"),
    ]},
    "jenkins": {"name": "Jenkins & CI/CD", "keywords": [
        Keyword("Jenkinsfile", "devops", 6, ("jenkins", "ci"), technology="jenkins"),
        Keyword("jenkins_home", "devops", 7, ("jenkins",), technology="jenkins"),
        Keyword("JENKINS_API_TOKEN", "devops", 9, ("jenkins", "credentials"), technology="jenkins"),
        Keyword(".github/workflows", "devops", 5, ("github", "ci"), technology="github-actions"),
        Keyword(".gitlab-ci.yml", "devops", 6, ("gitlab", "ci"), technology="gitlab-ci"),
        Keyword("CI_JOB_TOKEN", "devops", 8, ("gitlab", "ci", "credentials"), technology="gitlab-ci"),
    ]},
    "api": {"name": "API & Endpoints", "keywords": [
        Keyword("api_key", "api", 9, ("api", "key")),
        Keyword("API_KEY", "api", 9, ("api", "key")),
        Keyword("swagger", "api", 5, ("api", "docs")),
        Keyword("openapi", "api", 5, ("api", "docs")),
        Keyword("graphql", "api", 5, ("api", "graphql")),
        Keyword("/api/v1", "api", 4, ("api", "endpoint")),
        Keyword("/api/v2", "api", 4, ("api", "endpoint")),
        Keyword("swagger-ui.html", "api", 6, ("api", "docs")),
    ]},
    "auth": {"name": "Authentication", "keywords": [
        Keyword("login", "auth", 5, ("auth",)),
        Keyword("admin", "auth", 6, ("auth",)),
        Keyword("oauth", "auth", 6, ("auth", "oauth")),
        Keyword("sso", "auth", 5, ("auth", "sso")),
        Keyword("keycloak", "auth", 6, ("auth", "keycloak")),
        Keyword("okta", "auth", 5, ("auth", "okta")),
        Keyword("saml", "auth", 5, ("auth", "saml")),
    ]},
    "jwt": {"name": "JWT & Auth Tokens", "keywords": [
        Keyword("jwt", "auth", 7, ("jwt", "auth")),
        Keyword("JWT", "auth", 7, ("jwt", "auth")),
        Keyword("auth_token", "auth", 7, ("auth", "token")),
        Keyword("refresh_token", "auth", 8, ("auth", "token")),
        Keyword("oauth_token", "auth", 7, ("oauth", "token")),
        Keyword("eyJhbGciOi", "auth", 9, ("jwt", "leaked-token")),
    ]},
    "config_files": {"name": "Configuration Files", "keywords": [
        Keyword(".env", "config", 8, ("env", "config")),
        Keyword("config.php", "config", 7, ("php", "config")),
        Keyword("config.js", "config", 6, ("js", "config")),
        Keyword("config.json", "config", 6, ("json", "config")),
        Keyword("settings.py", "config", 7, ("python", "config")),
        Keyword("wp-config.php", "config", 8, ("wordpress", "config")),
        Keyword("web.config", "config", 7, ("iis", "config")),
        Keyword("nginx.conf", "config", 7, ("nginx", "config")),
        Keyword(".htaccess", "config", 6, ("apache", "config")),
        Keyword("application.properties", "config", 7, ("spring", "config")),
    ]},
    "wordpress": {"name": "WordPress", "keywords": [
        Keyword("wp-config.php", "cms", 8, ("wordpress", "config"), technology="wordpress"),
        Keyword("wp-content/uploads", "cms", 4, ("wordpress",), technology="wordpress"),
        Keyword("DB_PASSWORD", "cms", 8, ("wordpress", "database"), technology="wordpress"),
        Keyword("wp-admin", "cms", 5, ("wordpress", "admin"), technology="wordpress"),
        Keyword("xmlrpc.php", "cms", 5, ("wordpress",), technology="wordpress"),
        Keyword("wp-json/wp/v2/users", "cms", 5, ("wordpress", "api"), technology="wordpress"),
    ]},
    "laravel": {"name": "Laravel", "keywords": [
        Keyword("APP_KEY", "framework", 9, ("laravel", "key"), technology="laravel"),
        Keyword("laravel_session", "framework", 6, ("laravel",), technology="laravel"),
        Keyword(".env", "framework", 8, ("laravel", "env"), technology="laravel"),
        Keyword("storage/logs/laravel.log", "framework", 6, ("laravel", "logs"), technology="laravel"),
    ]},
    "django": {"name": "Django", "keywords": [
        Keyword("DJANGO_SETTINGS_MODULE", "framework", 7, ("django", "config"), technology="django"),
        Keyword("django_secret_key", "framework", 9, ("django", "key"), technology="django"),
        Keyword("SECRET_KEY", "framework", 9, ("django", "key"), technology="django"),
        Keyword("DEBUG = True", "framework", 6, ("django", "misconfig"), technology="django"),
    ]},
    "spring": {"name": "Spring Boot", "keywords": [
        Keyword("application.properties", "framework", 7, ("spring", "config"), technology="spring"),
        Keyword("application.yml", "framework", 7, ("spring", "config"), technology="spring"),
        Keyword("actuator", "framework", 6, ("spring", "monitoring"), technology="spring"),
        Keyword("actuator/env", "framework", 8, ("spring", "monitoring"), technology="spring"),
    ]},
    "nodejs": {"name": "Node.js", "keywords": [
        Keyword("package.json", "framework", 4, ("node", "config"), technology="nodejs"),
        Keyword("node_modules", "framework", 3, ("node",), technology="nodejs"),
        Keyword("express", "framework", 4, ("node", "express"), technology="nodejs"),
        Keyword("npm-debug.log", "framework", 5, ("node", "logs"), technology="nodejs"),
    ]},
    "react": {"name": "React", "keywords": [
        Keyword("REACT_APP_", "framework", 6, ("react", "env"), technology="react"),
        Keyword("react-scripts", "framework", 3, ("react",), technology="react"),
        Keyword("static/js/main", "framework", 3, ("react", "bundle"), technology="react"),
    ]},
    "angular": {"name": "Angular", "keywords": [
        Keyword("environment.prod.ts", "framework", 6, ("angular", "config"), technology="angular"),
        Keyword("ng-app", "framework", 3, ("angular",), technology="angular"),
        Keyword("angular.json", "framework", 4, ("angular", "config"), technology="angular"),
    ]},
    "nextjs": {"name": "Next.js", "keywords": [
        Keyword("NEXT_PUBLIC_", "framework", 5, ("nextjs", "env"), technology="nextjs"),
        Keyword("_next/static", "framework", 3, ("nextjs",), technology="nextjs"),
    ]},
    "monitoring": {"name": "Monitoring Tools", "keywords": [
        Keyword("grafana", "monitoring", 6, ("grafana",), technology="grafana"),
        Keyword("prometheus", "monitoring", 6, ("prometheus",), technology="prometheus"),
        Keyword("kibana", "monitoring", 6, ("kibana",), technology="elk"),
        Keyword("splunk", "monitoring", 6, ("splunk",), technology="splunk"),
        Keyword("datadog", "monitoring", 6, ("datadog",), technology="datadog"),
        Keyword("/api/datasources", "monitoring", 7, ("grafana", "api"), technology="grafana"),
    ]},
    "ai_services": {"name": "AI Services", "keywords": [
        Keyword("OPENAI_API_KEY", "ai", 9, ("openai", "credentials"), technology="openai"),
        Keyword("sk-", "ai", 8, ("openai", "leaked-key"), technology="openai"),
        Keyword("HUGGINGFACE_TOKEN", "ai", 8, ("huggingface", "credentials"), technology="huggingface"),
        Keyword("ANTHROPIC_API_KEY", "ai", 9, ("anthropic", "credentials"), technology="anthropic"),
        Keyword("AI_API_KEY", "ai", 8, ("ai", "credentials")),
        Keyword("COHERE_API_KEY", "ai", 8, ("cohere", "credentials"), technology="cohere"),
        Keyword("REPLICATE_API_TOKEN", "ai", 8, ("replicate", "credentials"), technology="replicate"),
    ]},
    "email": {"name": "Email & Messaging", "keywords": [
        Keyword("SMTP_PASSWORD", "email", 8, ("smtp", "credentials")),
        Keyword("SENDGRID_API_KEY", "email", 8, ("sendgrid", "credentials"), technology="sendgrid"),
        Keyword("MAIL_PASSWORD", "email", 8, ("mail", "credentials")),
        Keyword("mailto:", "email", 3, ("email",)),
    ]},
    "documents_sensitive": {"name": "Sensitive Document Language", "keywords": [
        Keyword("confidential", "documents", 6, ("document",)),
        Keyword("internal use only", "documents", 6, ("document",)),
        Keyword("do not distribute", "documents", 7, ("document",)),
        Keyword("classified", "documents", 7, ("document",)),
        Keyword("restricted", "documents", 6, ("document",)),
    ]},
    "medical": {"name": "Medical / Healthcare Records", "keywords": [
        Keyword("patient record", "sector", 8, ("healthcare", "phi")),
        Keyword("medical record", "sector", 8, ("healthcare", "phi")),
        Keyword("HIPAA", "sector", 5, ("healthcare", "compliance")),
        Keyword("diagnosis", "sector", 7, ("healthcare", "phi")),
        Keyword("insurance claim", "sector", 6, ("healthcare", "billing")),
    ]},
    "finance": {"name": "Finance / Banking Records", "keywords": [
        Keyword("account number", "sector", 8, ("finance", "pii")),
        Keyword("routing number", "sector", 8, ("finance", "pii")),
        Keyword("statement", "sector", 5, ("finance", "document")),
        Keyword("swift code", "sector", 6, ("finance",)),
        Keyword("PCI DSS", "sector", 5, ("finance", "compliance")),
    ]},
    "government": {"name": "Government Records", "keywords": [
        Keyword("for official use only", "sector", 7, ("government", "document")),
        Keyword("unclassified", "sector", 4, ("government", "document")),
        Keyword("procurement", "sector", 3, ("government",)),
        Keyword("RFP", "sector", 3, ("government",)),
    ]},
    "education": {"name": "Education Records", "keywords": [
        Keyword("student id", "sector", 6, ("education", "pii")),
        Keyword("FERPA", "sector", 5, ("education", "compliance")),
        Keyword("transcript", "sector", 6, ("education", "document")),
        Keyword("gradebook", "sector", 6, ("education", "document")),
    ]},
}
